### ISSUE TITLE
Support multiple instances

### ISSUE THREAD

**Issue by LukePrior** [oziee/ha-solcast-rooftop#1]
I haven't had a chance to try this out yet but does this integration allow me to provide multiple API calls where the results will be combined and returned as one for the energy dashboard predictions?

I have a North and a West API setup for my panels facing each way. I also didn't see how you have the refresh interval setup but I think it would be good if you got the sunrise and sunset times along with the number of active instances and dive that into 50.

For example 2 instances means 25 refrehes evenly spaced between sunrise and sunset to maximise the resolution and update speed.

Thanks for all your great work on these two integrations.

Cheers

**Comment by oziee** [comment]
It's 50 for the limit according to my api info solcast page
I have it set to every 2 hours

Since each integration is seperate I don't think the code can see how many instances there are (I but it might be able to with some ha code magic will have to see)

I can add the sun to set code like the other original code does

But I know it's returning the production as a 1000th so w instead of kw so I'll fix that tonight too

**Comment by oziee** [comment]
Each integration loaded does 2 api calls each time.. one for prediction and one for actual so that past prediction values are updated

If you have two instances of the integration then that would be 4 api per hour calls

I have not started the sun up down calling yet, I need to find time

**Comment by denisfrench** [comment]
I too have a split array, which seems to be a very common configuration, and specifically supported by Solcast (https://articles.solcast.com.au/en/articles/5000314-updated-permissions-for-home-pv-system-account).

I have created two instances of this integration against my two Solcast 'sites', and they both appear to be updating correctly. I understand that combining sites has not been implemented as yet, however neither seems to be showing on my Energy dashboard.

I have tried to add the forecasts through Configuration-Energy-Add Solar Production; my two Solcast devices show as options with checkboxes, but 'save' is greyed out whether either or both of them is ticked.

I am on HA core-2021.9.6. Is there something that I am missing? Any advice appreciated, thanks.

**Comment by oziee** [comment]
can you check the log on HA for any errors?
most likely I have been playing with the code and screwed something up
I have some new code that I have to put to github yet that only polls the api around sunny times 

every time I restart HA to debug the code it uses an api call so that gets annoying. but the code at most for two sites would poll the api two on start, once for current and once for past forecasts, and then every hr polls for the forecast updates
24+1 polls per site per day.. two rooftop sites would then use the total 50 api calls a day limit
limiting sunrise sunset around times would bring it under 50

not sure about the save problem, as I have a few listed and can tick and save them all

**Comment by denisfrench** [comment]
Sorry; my screw up actually!

I was trying to add the forecast production independantly of my solar production already set up in the home assistant settings. When I edit my existing solar production entry, I can indeed add the forecast production by ticking both boxes and save, and the total forecast production for both arrays is combined on the energy dashboard.

So yes, this integration works fine for a split array setup, including keeping within the 50 API call per day limit.

Thanks for your work on this :-)

**Comment by oziee** [comment]
good to hear..

I am currently testing the sunrise sunset code to make sure that its working before I push to GitHub
