### ISSUE TITLE
Show full forecast for today. Not just future.

### ISSUE THREAD

**Issue by B-Hartley** [oziee/ha-solcast-rooftop#5]
Is it possible for the integration to remember historic forecasts ?
At a minimum for today. But possibly a full history so I can see who the actual compares with the forecast ?

Thanks.

**Comment by oziee** [comment]
I'm testing the new code currently before the PR

It will show 6 days before and 6 days after

**Comment by LukePrior** [comment]
Is there any reason why the integration cannot store all of the last predictions?

Would be interesting to see.

**Comment by oziee** [comment]
It works just like the forecast.solar integration

I'm not storing it because it's just the forecast.. the actual generated solar data is important

**Comment by B-Hartley** [comment]
The difference is the forecast Solar API always delivers the complete forecast for today, so when you use that, you can see today's whole forecast and compare it to the actual.  
Solcast only delivers the future forecast, so you can't see what it was forecasting earlier.

I know there are other ways of checking that the SolCast accuracy is ok, I upload my actuals so I can compare on the Solcast site, but visually I like to see the forecast overlaid over today's actual production.  

It will be great if you can make it show 6 day of "historic forecast", I assume that's what you are saying it will do.

**Comment by oziee** [comment]
so I have cut the admin down to one.. ppl will have to create a rooftop site inside Solcast and use that resource_id

it polls the api every X (and I say X because in the settings you can choose between 1-6 hours between polling) hours.. People can then have 2 rooftop sites or more and calc the time between polling to stay within the 50 api calls max per day

the addon polls between 5am and 7pm, it also polls the actuate data twice a day at 12 and 7pm
1 rooftop site polling hourly will 17 times a day. 15 for the forecast and 2 for actual. (this does not include the 2 that happen when the addon is first install and run or when it polls every time HA is restarted)

if you have 2 roof top sites it will poll a total of 34 times a day
if you have more than 2 rooftop sites then in the setting changing the hours to 2 hourly would help keep to under 50 api calls a day

here is some shots of the addon now
<img width="324" alt="Screen Shot 2021-10-01 at 12 28 50 pm" src="https://user-images.githubusercontent.com/1471841/135556342-bd92b717-61ee-4dcd-95ed-2694714489bf.png">

<img width="267" alt="Screen Shot 2021-10-01 at 12 29 08 pm" src="https://user-images.githubusercontent.com/1471841/135556364-2049b282-aca8-4864-80e4-13c73d316cc6.png">

this shows the total forecast for today and tomorrow, the forecast for this hour and the next, and the number of api calls (again every time HA is restarted this resets to 0.. Solcast do not return an api counter with their data so this can't be tallied correctly)

<img width="628" alt="Screen Shot 2021-10-01 at 12 19 01 pm" src="https://user-images.githubusercontent.com/1471841/135556549-1cdd1621-9351-43d2-85d1-cb335f0b77ba.png">

here is what the graph looks like before the next actual api call updates the data

![before](https://user-images.githubusercontent.com/1471841/135556857-cb23d4da-6df2-494d-ac6b-225df479a834.png)
![after](https://user-images.githubusercontent.com/1471841/135556872-ff5b51ac-699e-4ea5-869c-f9b0d0c5b815.png)

**Comment by LukePrior** [comment]
This looks great I hope you upload the changes soon!

**Comment by oziee** [comment]
I am archiving this GitHub before I delete it..

I am going to just use the other as the main one now https://github.com/oziee/ha-solcast-solar

add that one to HA and remove this one.. I have just put the latest code up there
